apiVersion: apps/v1
kind: Deployment
metadata:
  name: targeting-service
  namespace: targeting-service
  labels:
    app: targeting-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: targeting-service
  template:
    metadata:
      labels:
        app: targeting-service
    spec:
      initContainers:
        - name: db-init
          image: postgres:15-alpine
          command:
            - sh
            - -c
            - psql "postgresql://$DB_USER:$DB_PASSWORD@$DB_HOST:$DB_PORT/$DB_NAME" -f /migrations/init.sql
          envFrom:
            - configMapRef:
                name: targeting-service-config
            - secretRef:
                name: targeting-service-secrets
          volumeMounts:
            - name: db-init
              mountPath: /migrations
      containers:
        - name: targeting-service
          image: 698173141574.dkr.ecr.us-east-1.amazonaws.com/targeting-service:v1.0.0-de99fca
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
            limits:
              cpu: "200m"
              memory: "250Mi"
          ports:
            - containerPort: 8003
          env:
            - name: DATABASE_URL
              value: "postgresql://$(DB_USER):$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(DB_NAME)"
          envFrom:
            - configMapRef:
                name: targeting-service-config
            - secretRef:
                name: targeting-service-secrets
          readinessProbe:
            httpGet:
              path: /health
              port: 8003
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8003
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 3
      volumes:
        - name: db-init
          configMap:
            name: targeting-service-db-init
