apiVersion: v1
kind: ConfigMap
metadata:
  name: analytics-service-config
  namespace: analytics-service
data:
  PORT: "8005"
  AWS_REGION: "us-east-1"
  AWS_SQS_URL: "https://sqs.us-east-1.amazonaws.com/698173141574/analytics-queue-sqs-queue"
  AWS_DYNAMODB_TABLE: "ToggleMasterAnalytics"
  # AWS_ACCESS_KEY_ID: "REPLACE_ME_ACCESS_KEY_ID"
  # AWS_SECRET_ACCESS_KEY: "REPLACE_ME_SECRET_ACCESS_KEY"
  # AWS_SQS_ENDPOINT: "REPLACE_ME_SQS_ENDPOINT"
  # AWS_DYNAMODB_ENDPOINT: "REPLACE_ME_DYNAMODB_ENDPOINT"
  OTEL_SERVICE_NAME: "analytics-service"
  OTEL_EXPORTER_OTLP_ENDPOINT: "otel-collector.monitoring.svc.cluster.local:4317"
  OTEL_EXPORTER_OTLP_INSECURE: "true"
  OTEL_METRIC_EXPORT_INTERVAL: "15000"
