apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: analytics-service
  namespace: analytics-service
spec:
  scaleTargetRef:
    name: analytics-service
  minReplicaCount: 0
  maxReplicaCount: 2
  triggers:
    - type: aws-sqs-queue
      metadata:
        queueURL: "https://sqs.us-east-1.amazonaws.com/698173141574/analytics-queue-sqs-queue"
        queueLength: "1"
        awsRegion: "us-east-1"
      authenticationRef:
        name: analytics-service-aws-auth
