apiVersion: v1
kind: ConfigMap
metadata:
  name: flag-service-config
  namespace: flag-service
data:
  PORT: "8002"
  AUTH_SERVICE_URL: "http://auth-service.auth-service.svc.cluster.local:8001"
  OTEL_SERVICE_NAME: "flag-service"
  OTEL_EXPORTER_OTLP_ENDPOINT: "otel-collector.monitoring.svc.cluster.local:4317"
  OTEL_EXPORTER_OTLP_INSECURE: "true"
  OTEL_METRIC_EXPORT_INTERVAL: "15000"
