apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: alertmanager-notification-credentials
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: alertmanager-notification-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: pagerduty-routing-key
      remoteRef:
        key: eks/alert-notifications
        property: pagerduty-routing-key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: discord-webhook-url
      remoteRef:
        key: eks/alert-notifications
        property: discord-webhook-url
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
