apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: newrelic-otlp-credentials
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: newrelic-otlp-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: license-key
      remoteRef:
        key: eks/newrelic
        property: license-key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
