name: CI - evaluation-service

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "evaluation-service/**"
  pull_request:
    branches: [main]
    paths:
      - "evaluation-service/**"

permissions:
  contents: write
  id-token: write

jobs:
  ci:
    uses: ./.github/workflows/_ci-go.yml
    with:
      service: evaluation-service
      ecr_repo: evaluation-service
    secrets: inherit
