name: CI - targeting-service

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "targeting-service/**"
  pull_request:
    branches: [main]
    paths:
      - "targeting-service/**"

permissions:
  contents: write
  id-token: write

jobs:
  ci:
    uses: ./.github/workflows/_ci-python.yml
    with:
      service: targeting-service
      ecr_repo: targeting-service
    secrets: inherit
